services:
  postgres:
    image: postgres:16-alpine
    container_name: fp-training-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fp_training}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - '5432:5432'
    volumes:
      - fp-training-postgres-data:/var/lib/postgresql/data

volumes:
  fp-training-postgres-data:
